config/routes.rb
Imptest::Application.routes.draw do

  match '/push' => 'sensors#push'

  resources :sensors

  root :to => 'pages#main'
  
end

app/models/sample.rb
class Sample < ActiveRecord::Base
  attr_accessible :sensor_id, :value


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def main
	end

end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController

	def new
		@sample = Sample.new
	end

	def create
		@sample = Sample.new(params[:sample])
		@sample.save
	end

	def push
		@value = params[:value].split(':')
		@channel = params[:channel]
		
		if(@value[0] == "Avg")
			@sample = Sample.new
			@sample.value = @value[1]
			@sample.sensor_id = @channel
			@sample.save
		end
		
		while Sample.count > 7500
			Sample.order("created_at").first.delete
		end
		render :nothing => true
	end

	def index
		@samples = Sample.order("created_at DESC").limit(25)
		@chart_samples = Sample.order("created_at DESC")
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= @title %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
	<body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">      
        <div class="container">      
          <ul class="nav">
            
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/pages/main.html.erb
<h2>Welcome!</h2>

<%= link_to "Data Table", sensors_path %>

app/views/sensors/index.html.erb
<h2>Current Readings</h2>

<%= content_tag :div, "", id: "soil_moisture_chart", data: {sensors: @chart_samples} %>
	
<table class="table table-striped table-bordered table-condensed">
	<thead>
		<th style="width: 10em">Sensor Channel</th>
		<th style="width: 10em">Reading</th>
		<th style="width: 15em">Timestamp (UTC)</th>
		<th style="width: 15em">Timestamp</th>
		<th></th>
	</thead>
	<% @samples.each do |s| %>
		<tbody>
			<% if s.sensor_id %>
				<td><%= s.sensor_id %></td>
				<td><%= number_to_percentage(s.value * 100, :precision => 0) if s.value %></td>
				<td><%= s.created_at %></td>
				<td><%= s.created_at.localtime %></td>
				<td></td>
			<% end %>
		</tbody>
	<% end %>
</table>


app/views/sensors/new.html.erb
<h3>Add Sensor Data...</h3>

<%= form_for @sample do |f| %>
	<%= f.label "Value" %>
	<%= f.text_field :value %>
	<%= f.submit %>
M% end %>